### ISSUE TITLE
Add more providers.

### ISSUE THREAD

**Issue by Samy20023** [LagradOst/CloudStream-3#14]
Hi,

Can you add the cloudstream 2 anime and movies providers in this app .

Anime provides:
 
1- shiro 
2- vidstreaming
3- animekisa
4- animeparadise 
5- 4 anime 
6- arrayanime 
7- genoanime 

Movies providers:

1- 123filesclub 
2- vidsrc
3- watchtv
4- livemovies123
5- themovies123
6- watchseries 
7- gomostream
8- movies123
9- themovie
10- monkeystream
11- lookmovie 

Add all this providers in update and if there problems in any one of this providers, don't add it .The app will be amazing and thank you for your efforts 🙏.

**Comment by ArjixWasTaken** [comment]
1. Shiro - Shiro has changed it's api and fucked us over, originally it was the first provider cs-3 had, but it was removed before release.
2. Vidstreaming - We already have gogoanime, so there is no reason to add it (it gets its anime from gogoanime)
3. animekisa - We already have gogoanime, so there is no reason to add it (it gets its anime from gogoanime)
5. 4anime - the site is fucking dead
6. arrayanime - We already have gogoanime, so there is no reason to add it (it gets its anime from gogoanime)
7. genoanime - We already have gogoanime, so there is no reason to add it (it gets its anime from gogoanime)

I might add animeparadise, but other than that none of the anime sites in ur list is going to be added.

(I'm not talking about the movie sites since I don't plan to do any myself.)

**Comment by ArjixWasTaken** [comment]
But this makes me to not want to add animeparadise
```
We will be down for a little while due to backend issues.

You are being redirected to our partner, shiro.is.
```

Like, the site is down for half the day everyday due to google drive rate-limits 🤣🤣🤣

**Comment by Samy20023** [comment]
Thanks
