### ISSUE TITLE
Some media not playing and the UI redesign

### ISSUE THREAD

**Issue by JasonSmith20** [LagradOst/CloudStream-3#213]
Hello I was wondering in the next update could you possibly give the app UI a more NETFLIX feel to it as it would help a lot and some of the sites take longer to  load a video and stick in the middle I was hoping you could fix these other than that the recent update has been well keep up the good work as always.

**Comment by LagradOst** [comment]
Well, I cant redesign the app without any examples on where to improve. Also loading and speed cant be improved as I dont host any content.

**Comment by Jasonsmith236** [comment]
Ok so I found the shiro apps UI to be more appealing than this one and the custom colors feature was great so and the previous episode button was great too so since you were the creator of shiro I was wondering if you could include things from the app and cloudstream 2 which also had more features it would be the best combination trust me also I know it won't be easy but I was just making suggestions to make the app better.
