### ISSUE TITLE
Tv series and vpn

### ISSUE THREAD

**Issue by Recoil1024** [LagradOst/CloudStream-3#261]
Man app is great for anime but pls add sites for tv series because most of the time I have to use vpn to get access to episodes and also the vidembed site works without vpn but it always say no link found when any episode is opened but when accessed on browser site works perfectly

**Comment by LagradOst** [comment]
Add url to the sites you want added so I can label this as a provider

**Comment by ArjixWasTaken** [comment]
> Man app is great for anime but pls add sites for tv series

This sentence, implies that there are no providers for tv series...
Adding a "more" in that sentence fixes the issue with that sentence.

Please read what you send before you send it, because most of the time we don't care enough to understand what your intention is.

With this alone I could just reply "But there are tv series providers in-app" and be done with this.
Do you see the problem? Because you did not phrase what you meant correctly you did not get the desired answer.

Of course I did understand what you meant by reading the rest of the message, but at that point I was already frustrated by the little amount of brain power that went into the making of that sentence.

And as @LagradOst, please provide sites that you think we should add, if you really want a site to be added, then give a link to that site.
Don't make us search for a site on our own, 'cause we won't do that, we have better things to waste our time on (like playing minecraft).

**Comment by JasonSmith20** [comment]
This request makes no sense at all its not structured correctly because tv series are there.

**Comment by Recoil1024** [comment]
Sorry but English is not my first language and https://www7.bflix.to/    is
quite good for tv series and movies , also I have a little list of sites I
can share if you want

**Comment by cutterchop** [comment]
> > Man app is great for anime but pls add sites for tv series
> 
> This sentence, implies that there are no providers for tv series... Adding a "more" in that sentence fixes the issue with that sentence.
> 
> Please read what you send before you send it, because most of the time we don't care enough to try and understand what your intention is.
> 
> With this alone I could just reply "But there are tv series providers in-app" and be done with this. Do you see the problem? Because you did not phrase what you meant correctly you did not get the desired answer.
> 
> Of course I did understand what you meant by reading the rest of the message, but at that point I was already frustrated by the little amount of brain power that went into the making of that sentence.
> 
> And as @LagradOst said, please provide sites that you think we should add, if you really want a site to be added, then give a link to that site. Don't make us search for a site on our own, 'cause we won't do that, we have better things to waste our time on (like playing minecraft).

Ok but why u crying :1?

**Comment by Recoil1024** [comment]
For your question that why I am crying its because my exam results
committed suicide 🙃🙃
