### ISSUE TITLE
WebView sniffing 

### ISSUE THREAD

**Issue by FreeDTV** [LagradOst/CloudStream-3#296]
Can it support WebView sniffing function?

**Comment by ArjixWasTaken** [comment]
I bet you closed this because you already got your answer, but I'll answer either way.
can what support webview sniffing?
and what do you mean by webview sniffing?

Did you actually want to say if we can use a webview and monitor its network requests?
If so then yes, it's already done in some providers as well.

**Comment by FreeDTV** [comment]
WebView intercepts and filters the playback link through shouldInterceptRequest.

It is closed because obtaining success through API does not see the above solution.

**Comment by FreeDTV** [comment]
> I bet you closed this because you already got your answer, but I'll answer either way. can what support webview sniffing? and what do you mean by webview sniffing?
> 
> Did you actually want to say if we can use a webview and monitor its network requests? If so then yes, it's already done in some providers as well.

WebView intercepts and filters the playback link through shouldInterceptRequest.

It is closed because obtaining success through API does not see the above solution.
