### ISSUE TITLE
[Feature Request] Bold/italic option in subtitles

### ISSUE THREAD

**Issue by niraularohan** [LagradOst/CloudStream-3#314]
Can you guys please add bold and italic options in subtitles menu? I want the text to be bold but there ain't any option for that. Yeah, it has size customization but thay just makes text bigger in size.
Hope "bold" can/will be added.

**Comment by LagradOst** [comment]
That might collide with subtitles ability to have italic and bold text. It is not a built in option for font customization by exoplayer at least. Normaly the subtitles themself decide if text is italic or not like this (in srt/vtt format):
`1`
`00:03:26,563 --> 00:03:29,657`
`<i> This text is in italics. </i>`
`This text is not in italics`

So that is the reason I am not really keen on adding it.
