### ISSUE TITLE
faselhd.io, cima4uu.club, egy.best

### ISSUE THREAD

**Issue by ZOUHAIRRICH** [LagradOst/CloudStream-3#469]
for Arabic providers, I suggest you add faselhd.io and cima4uu.club and shahid4u.tv and egy.best ...  and Thanks for this great app.

**Comment by cutterchop** [comment]
> for Arabic providers, I suggest you add faselhd.io and cima4uu.club and shahid4u.tv and egy.best ... and Thanks for this great app.

hello Zouhairrich, 
about your suggestion 
Firstly FaselHD can't be added due to cloudflare protection and many shows/films missing.

![image](https://user-images.githubusercontent.com/31880937/149681858-79a88eda-84b0-4710-9872-890d943ca62b.png)
![image](https://user-images.githubusercontent.com/31880937/149681947-c897b64e-4191-4142-8d8f-f3101e112b92.png)

Secondly Cima4u can't be added due to its extremely bad design making it impossible to scrape without achiveing a head tumor plus most of its stuff are 'expired' as well.

![image](https://user-images.githubusercontent.com/31880937/149681921-759676f4-2413-41f8-a76f-73b9fcae1e71.png)

egy.best has the most annoying logo between them all , you can watch its bearble but why use it if there is better alternatives,
egy best has an ip ban on it and other stuff that makes it hard to scrape 
![image](https://user-images.githubusercontent.com/31880937/149682113-513ecaaa-9994-4deb-8cc5-1b2959a433d6.png)

in the end i don't know if you checked the previous beta update a new site was added by the name akwam. 

here is the latest beta https://github.com/LagradOst/CloudStream-3/releases/download/pre-release/app-prerelease.apk
download it and from there go to settings 

![image](https://user-images.githubusercontent.com/31880937/149682189-ec9bbc66-1e55-4170-8fb5-82030bd8f1b8.png)

toggle arabic inside that setting and then go to the search section and activate akwam 

![image](https://user-images.githubusercontent.com/31880937/149682208-2c0b78c4-5b1b-4583-a12b-7cfa9686d36d.png)
