### ISSUE TITLE
Trailers.to not working

### ISSUE THREAD

**Issue by Zeroo097** [LagradOst/CloudStream-3#545]
Whenever I try to stream any movie or show it just displays an image(tagging below)but it plays fine on the site.
![Screenshot_20220131-144837.jpg](https://user-images.githubusercontent.com/91909890/151767888-603c84c7-067e-4c8e-b6d7-df638e1ef99c.jpg)

**Comment by ITADORI-15** [comment]
Yeah same

**Comment by ORRNY66** [comment]
The problem is this. Take, for example, the address Avengers: Endgame https://trailers.to/video/cloudstream/imdb/tt4154796 this address translates to https://cdn2.tech-school.click/web-sources/cloudstream/0/imdb-tt4154796 ~ .mp4 and in this address there is an error more precisely in this cloudstream / 0 / imdb-tt4154796 instead of zero give the movie ID from https://trailers.to/en/movie/220/avengers-endgame-2019 so 220. The resulting address will be thus https://cdn2.tech-school.click/web-sources/cloudstream/220/imdb-tt4154796~.mp4 which already works.

**Comment by Zeroo097** [comment]
I don't have a single clue about what you just wrote

**Comment by LagradOst** [comment]
> The problem is this. Take, for example, the address Avengers: Endgame https://trailers.to/video/cloudstream/imdb/tt4154796 this address translates to https://cdn2.tech-school.click/web-sources/cloudstream/0/imdb-tt4154796 ~ .mp4 and in this address there is an error more precisely in this cloudstream / 0 / imdb-tt4154796 instead of zero give the movie ID from https://trailers.to/en/movie/220/avengers-endgame-2019 so 220. The resulting address will be thus https://cdn2.tech-school.click/web-sources/cloudstream/220/imdb-tt4154796~.mp4 which already works.

intresting, however that is not detailed in the api for some reason

**Comment by ORRNY66** [comment]
@Zeroo097

https://user-images.githubusercontent.com/5471789/151795110-85865452-3556-4256-8183-ae0615a3efd8.mp4

**Comment by ORRNY66** [comment]
I also came across this if you change the movie ID, for example, at the address to Avengers: Endgame, instead of 220, you put another movie ID 45335 there, so the address still works, even if the final IMDB ID has not changed.

https://cdn2.tech-school.click/web-sources/cloudstream/220/imdb-tt4154796~.mp4

https://cdn2.tech-school.click/web-sources/cloudstream/45335/imdb-tt4154796~.mp4
