### ISSUE TITLE
Feature(s) Request: Dedicated Pop-Up Button & Portrait Mode

### ISSUE THREAD

**Issue by Gthbacc** [LagradOst/CloudStream-3#547]
Basically as mentioned in the title.
Portrait mode would be really neat to have since i dont like being forced to watch it in landscape and The Pop Up button next to the source/next episode button would be very nice.
Thanks in advance.

**Comment by Gthbacc** [comment]
Ok that was quick lol.
May I ask why won't these features be added? I for one think the pop up button is gonna be super useful.

**Comment by Duoquadragesimal** [comment]
The pop-up button one i don't understand because you can literally just press the home button. The portrait mode idea is very niche but you do you I guess. But because it's so niche, a better idea would be you finding a solution instead of them implementing one into the app. Like, other bigger apps like Netflix don't have that as an option.The free app [Rotation Control](https://play.google.com/store/apps/details?id=org.crape.rotationcontrol) allows you to lock rotation on CloudStream3 so that you can watch videos in portrait, might be a good solution for you if that's your preferred method of viewing content. @Gthbacc

**Comment by LagradOst** [comment]
#88
