### ISSUE TITLE
Consumes too much data

### ISSUE THREAD

**Issue by umarvirk12** [LagradOst/CloudStream-3#59]
It would be great to have a lite version, so that the app doesn't consume too much data. I barely watched something for 3 minutes and it took around 100 mb of my data, why is that?

**Comment by ArjixWasTaken** [comment]
> I barely watched something for 3 minutes and it took around 100 mb of my data

Uhh...did you use trailers.to?
The movies/tvshows it has are huge in filesizes.

> It would be great to have a lite version, so that the app doesn't consume too much data

Nah, no lite version will be there, we will add cache to reuse data instead of requesting it again instead.
When is such a thing coming? Dunno, ask @LagradOst ![image](https://user-images.githubusercontent.com/53124886/131805196-9b881126-f7af-4c15-abb8-f14aab4e0b1a.png)

**Comment by LagradOst** [comment]
I think lag added videoplayer cache, but a lite mode wont be implemented. My best suggestion is for you to download the episodes beforehand. If you have a better idea on how to handle traffic while in cellular mode, write because we cant compress files.

**Comment by ArjixWasTaken** [comment]
> write because we cant compress files.

Even if we compressed the files, it would not reduce the cellular usage.

**Comment by LagradOst** [comment]
> 
> 
> > write because we cant compress files.
> 
> Even if we compressed the files, it would not reduce the cellular usage.

that is what I meant :pain:

**Comment by LagradOst** [comment]
Lag implemented cashing in the videoplayer, closing this issue as this is the most we can do.
