### ISSUE TITLE
Open keyboard automatically as the search icon is clicked.

### ISSUE THREAD

**Issue by Mesum-Hussain** [LagradOst/CloudStream-3#904]
**Guidelines:**
- [✓] It **is not** a duplicate issue.
- [✓] It **is not** a request to add a website. Write it here instead https://github.com/LagradOst/CloudStream-3/issues/24

**Choose one of the following:**
- [✓] UI/UX enhancement
- New feature
- Other

**Describe your request here** *(fill this up)*

How it works:
As I click the search icon in the navigation bar at the bottom, I go to the search tab but the keyboard doesn't show up immediately. I have to redundantly click the search field again to make the keyboard appear. Please make the keyboard appear automatically as soon as the search icon is clicked and we go to the search activity.

Issues it solves:
It's eliminates the need of redundant act of clicking the search bar again to make the keyboard appear, hence improving the user experience.

Why it is needed:
This feature improves the user experience.

- [✓] How it works.
- [✓] Issues it solves.
- [✓] Why it is needed.

**Other related info**

**Comment by LagradOst** [comment]
I actually had this in a previous version of cs3, but some problems occurred with it and was removed.
1. [UX] There is no diffrence between clicking the search icon and returning to search from a title, this causes search to be pulled up in situations where you already have search results active.
2. [UX] The user might just want to quicksearch with the history
3. [BUG] A very annoying bug will happened if I try to trigger the focus via code, namely that it will trigger on every search result for no reason and that is why I really dont want to touch search at all.
4. [BUG] Due to androids layer structure with UI the search will pop up (only for some users) when re entering the app even if they are not on search if they have navigated to a resultpage via search
5. [BUG] This causes problems with pulling up the search for androidTV

The bugs can maybe be fixed however I do not trust android with any sort of autofocus on search at all and that is why this is denied

**Comment by cutterchop** [comment]
> **Guidelines:**
> 
> * [✓] It **is not** a duplicate issue.
> * [✓] It **is not** a request to add a website. Write it here instead [[providers] Some sites #24](https://github.com/LagradOst/CloudStream-3/issues/24)
> 
> **Choose one of the following:**
> 
> * [✓] UI/UX enhancement
> * New feature
> * Other
> 
> **Describe your request here** _(fill this up)_
> 
> How it works: As I click the search icon in the navigation bar at the bottom, I go to the search tab but the keyboard doesn't show up immediately. I have to redundantly click the search field again to make the keyboard appear. Please make the keyboard appear automatically as soon as the search icon is clicked and we go to the search activity.
> 
> Issues it solves: It's eliminates the need of redundant act of clicking the search bar again to make the keyboard appear, hence improving the user experience.
> 
> Why it is needed: This feature improves the user experience.
> 
> * [✓] How it works.
> * [✓] Issues it solves.
> * [✓] Why it is needed.
> 
> **Other related info**

Just like blue said, this type of a feature was very frustrating on the app, lots of bugs, many users reported it till the point it was removed sorry
