### ISSUE TITLE
Chromecast won't work. 

### ISSUE THREAD

**Issue by transferableethos** [LagradOst/CloudStream-3#909]
I've been trying to cast media to the TV. The loading icon shows up for a while and goes away. Nothing happens. I have also tried casting from all the sources available and it still won't work. Any idea on how to fix this?

**Comment by LagradOst** [comment]
3. Why is chromecasting not working?
If you can't start casting it's because the app doesn't find you TV on your network. VPN/Firewalls/wrong network may cause this.

If the videos won't load it's likely either due to:
The provider/video host simply not supporting casting (referer blocked), we can't fix this. 
You are using a VPN, most video links are IP blocked meaning that casting will fail if you are connected to a VPN.
=======================
I tested and it works for me on latest pre

**Comment by transferableethos** [comment]
I don't have a problem with casting on anything else though. I've used the links from the app to cast through Web video cast app and it works fine. The only trouble I'm getting is through the app itself.
